version: 2.0

jobs:

    build-docker:
        docker:
            - image: docker:19-git
        working_directory: /ws/opencog-docker
        steps:
            - setup_remote_docker
            - run:
                name: Echo arguments
                command: |
                    echo DOCKER_BRANCH=$DOCKER_BRANCH
                    echo DOCKER_REPO=$DOCKER_REPO
                    echo DOCKER_USERNAME=$DOCKER_USERNAME
            - run:
                name: Clone docker repo
                command: |
                    git clone --depth=1 -b $DOCKER_BRANCH $DOCKER_REPO .
            - run:
                name: Build opencog-deps image
                command: |
                    cd ./opencog
                    # TODO: add parameters:
                    # - ocpkg path
                    # - testdatasets path ?
                    #sh ./docker-build.sh -u -b
                    sh ./docker-build.sh -b
                    docker tag singularitynet/opencog-deps:latest vsbogdcircleci/singularitynet:deps
                    echo "$DOCKER_PASSWORD" | docker login --username=$DOCKER_USERNAME --password-stdin
                    docker push vsbogdcircleci/singularitynet:deps

    build-cogutil:
        docker:
            - image: vsbogdcircleci/singularitynet:deps
              user: root
              auth:
                  username: $DOCKER_USERNAME
                  password: $DOCKER_PASSWORD
        working_directory: /ws/cogutil
        steps:
            - run:
                name: Echo arguments
                command: |
                    echo COGUTIL_BRANCH=$COGUTIL_BRANCH
                    echo COGUTIL_REPO=$COGUTIL_REPO
            - run:
                name: Build
                command: |
                    git clone --depth 1 -b $COGUTIL_BRANCH $COGUTIL_REPO .
                    mkdir -p build
                    cd build
                    cmake ..
                    make
                    make tests
                    make test

workflows:
    version: 2
    complete_build:
        jobs:
            - build-docker:
                context: dockerhub
            - build-cogutil:
                context: dockerhub
                requires:
                    - build-docker
