version: 2.0

jobs:
    build-docker:
        docker:
            - image: docker:19-git
        working_directory: /ws/opencog-docker
        steps:
            - attach_workspace:
                at: /ws
            - run:
                name: Echo arguments
                command: |
                    echo DOCKER_BRANCH=$DOCKER_BRANCH
                    echo DOCKER_REPO=$DOCKER_REPO
            - setup_remote_docker
            - run:
                name: Checkout opencog-docker repo
                command: git clone --depth=1 -b $DOCKER_BRANCH $DOCKER_REPO .
            # TODO: add path to the ocpkg as parameter
            - run:
                name: Build opencog-deps image
                command: |
                    cd ./opencog
                    #sh ./docker-build.sh -u -b
                    docker build -t singularitynet/opencog-deps:int base
                    docker save -o /ws/opencog-deps.tgz singularitynet/opencog-deps:int
            - persist_to_workspace:
                root: /ws
                paths:
                    - opencog-deps.tgz

    inject-docker:
        docker:
            - image: docker:19-git
        steps:
            - attach_workspace:
                at: /ws
            - run:
                name: Load docker image
                command: docker load -i /ws/opencog-deps.tgz

    build-cogutil:
        docker:
            - image: singularitynet/opencog-deps:int
        working_directory: /ws/cogutil
        steps:
            - run:
                name: Echo arguments
                command: |
                    echo COGUTIL_BRANCH=$COGUTIL_BRANCH
                    echo COGUTIL_REPO=$COGUTIL_REPO
            - run:
                name: Clone cogutil
                command: git clone --depth 1 -b $COGUTIL_BRANCH $COGUTIL_REPO .

workflows:
    version: 2
    complete_build:
        jobs:
            - build-docker
            - inject-docker:
                requires:
                    - build-docker
            - build-cogutil:
                requires:
                    - inject-docker
